### ISSUE TITLE
Is the module fully transpiled?

### ISSUE THREAD

**Issue by bahmutov** [yamalight/graffiti#11]
Getting `?.` syntax trying to run the example

```
/Users/gleb/git/default-queries/node_modules/graffiti/lib/index.js:65
  await Promise.all(plugins.map((plugin) => plugin.setup?.({ server })));
```

full terminal output

```
$ curl https://codeload.github.com/yamalight/graffiti/tar.gz/master | tar -xz --strip=2 graffiti-master/examples/default-queries
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1158k    0 1158k    0     0  2469k      0 --:--:-- --:--:-- --:--:-- 2469k
~/git on master
$ cd default-queries/
~/git/default-queries on master
$ ls
README.md		graffiti.config.js	package.json		schema
~/git/default-queries on master
$ npm i

> nodemon@2.0.4 postinstall /Users/gleb/git/default-queries/node_modules/nodemon
> node bin/postinstall || exit 0

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for graffiti@1.1.1: wanted: {"node":">=14.8.0"} (current: {"node":"12.14.1","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: graffiti@1.1.1

added 300 packages from 154 contributors and audited 300 packages in 10.202s

35 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

~/git/default-queries on master
$ npm start

> example-default-queries@0.1.0 start /Users/gleb/git/default-queries
> graffiti

/Users/gleb/git/default-queries/node_modules/graffiti/lib/index.js:65
  await Promise.all(plugins.map((plugin) => plugin.setup?.({ server })));
                                                         ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)

```

**Comment by yamalight** [comment]
@bahmutov minimum Node version Graffiti targets is 14.x (so, optional chaining is supported out of the box). I'm guessing you are using the older version?

**Comment by bahmutov** [comment]
Yeah 12.14, sure I can use newer version - would be nice to list in readme or package json

**Comment by yamalight** [comment]
`package.json` already does include `engines` clause! 
Would be a good idea to add it to readme though 🤔

**Comment by bahmutov** [comment]
Not in the examples :)

```
{
  "name": "example-default-queries",
  "version": "0.1.0",
  "description": "",
  "private": "true",
  "scripts": {
    "start": "graffiti",
    "develop": "graffiti dev"
  },
  "keywords": [],
  "author": "Tim Ermilov <yamalight@gmail.com> (http://codezen.net)",
  "license": "MIT",
  "dependencies": {
    "graffiti": "*"
  }
}
```

**Comment by bahmutov** [comment]
Also, just for simplifying trying it out, would be nice to mention how to run Mongo locally, probably a Docker command to start an instance would be enough

**Comment by yamalight** [comment]
@bahmutov ah! fair point, will add it to examples as well!
docker command to start a mongo is available in tutorial - suggestions on other fitting places for that? :)

**Comment by yamalight** [comment]
Should now be included in most places where it makes sense (to me at least).
If you feel that's not enough - please let me know where else it'd make sense :)
